### ISSUE TITLE
Can you provide more morphological examples in this code?

### ISSUE THREAD

**Issue by Alan-Leo-Wong** [sgsellan/opening-and-closing-surfaces#2]
Hi,
I see this code seems only provide the closing operation, where are the opening, dilation and erosion? 
Thanks a lot.

**Comment by sgsellan** [comment]
Hi!

The closing code has an `opening` flag that reverses the flow and computes the opening. However, as explained in the paper, this method cannot compute dilation and erosions (you can look at, for example, [this implementation](https://github.com/libigl/libigl/blob/main/include/igl/offset_surface.h) if you're looking for efficient mesh dilation/erosion morphology).
